### ISSUE TITLE
7.02 Jailbreak

### ISSUE THREAD

**Issue by djkilla1337** [DizzRL/ps4-bo3-gsc-injector#1]
It doesn't connect to my console on 7.02 bro.

**Comment by trister1997** [comment]
This tool piggy backs off PS4 Toolbox for the payload, make sure you use binloader to connect to PS4 toolbox first then try again.

**Comment by DizzRL** [comment]
This tool piggybacks off PS4 Toolbox, make sure you use bin loader to connect to PS4 toolbox first, then it should work.

**Comment by djkilla1337** [comment]
Okay thank you bro I will give it a test now

**Comment by djkilla1337** [comment]
thank you bro it works :) [https://gyazo.com/a3ebd7febde1fbcf49a51327523a9fc2](url)
