### ISSUE TITLE
It won't let me inject

### ISSUE THREAD

**Issue by MrPezi** [DizzRL/ps4-bo3-gsc-injector#5]
Every time I click inject, it always says "Unhandled exception has occurred in your application." and then says "libdbg status 0x0"

**Comment by trister1997** [comment]
Is you PS4 on 7.55? I am currently working on 7.55 support.

**Comment by someguythatmods** [comment]
Are you on 7.55? I am currently working on 7.55 support.

**Comment by someguythatmods** [comment]
Closing due to no reply.
